config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'tasks', to: 'tasks#index'
  # get 'tasks/new', to: 'tasks#new', as: 'new_task'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/:id', to: 'tasks#show', as: 'task'

  # get "tasks/:id/edit", to: "tasks#edit", as: 'edit_task'
  # patch "tasks/:id", to: "tasks#update"
  # delete 'tasks/:id', to: 'tasks#destroy'


  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: [:show, :edit, :update, :destroy] #! not to repeat several time set_task method

  def index
    @tasks = Task.all
  end

  def show
  end
  
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit  
  end 

  def update
    @task.update(update_task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_tasks
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def update_task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/61b755c568.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
   <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %> 

app/views/tasks/index.html.erb
<h1>My Task</h1>

<ul>
  <% @tasks.each do |task| %> 
    <li>  <%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

<%= link_to 'Create a task', new_task_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>hello</h1>

<ul>
  <li> <%= @task.title %> </li>
  <li><%= @task.details %></li>
  <li> <%= @task.completed %></li>
</ul>

<ul>
  <li><%= link_to 'Edit the task', edit_task_path(@task) %> </li> 
  <li>
    <%= link_to task_path(@task), method: :delete, data: { confirm: "Are you sure?" } do %>
      Delete <i class="fas fa-trash"></i>
    <% end %>
  </li>
</ul>
<%= link_to 'See all tasks', tasks_path %> 